'use client'

import { useState } from 'react'
import { Copy, Download, Printer, Share2 } from 'lucide-react'
import { pdf, Document, Page, Text, StyleSheet } from '@react-pdf/renderer'

type Props = { title: string; description?: string | null; ingredients: Array<{ name: string; quantity?: string; unit?: string }>; instructions: Array<{ instruction: string }> }
const styles = StyleSheet.create({ page: { padding: 44, fontSize: 11, color: '#27231e' }, title: { fontSize: 28, marginBottom: 10 }, section: { marginTop: 22, fontSize: 16, marginBottom: 8 }, line: { marginBottom: 6, lineHeight: 1.4 } })
function RecipeDocument({ title, description, ingredients, instructions }: Props) { return <Document><Page size="A4" style={styles.page}><Text style={styles.title}>{title}</Text>{description && <Text style={styles.line}>{description}</Text>}<Text style={styles.section}>Ingredients</Text>{ingredients.map((item, index) => <Text key={index} style={styles.line}>• {[item.quantity, item.unit, item.name].filter(Boolean).join(' ')}</Text>)}<Text style={styles.section}>Method</Text>{instructions.map((item, index) => <Text key={index} style={styles.line}>{index + 1}. {item.instruction}</Text>)}</Page></Document> }
export function RecipeActions(props: Props) { const [busy, setBusy] = useState(false); async function share() { const url = window.location.href; if (navigator.share) { try { await navigator.share({ title: props.title, text: props.description ?? 'A recipe from crumb.', url }) } catch {} } else { await navigator.clipboard.writeText(url); window.alert('Link copied to clipboard') } } async function download() { setBusy(true); try { const blob = await pdf(<RecipeDocument {...props} />).toBlob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${props.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`; anchor.click(); URL.revokeObjectURL(url) } catch { window.alert('Could not create the PDF. Try printing instead.') } finally { setBusy(false) } } return <div className="flex flex-wrap items-center gap-2"><button onClick={share} className="flex items-center gap-2 rounded-full border border-border px-3 py-2 text-sm"><Share2 size={16} /> Share</button><button onClick={() => window.print()} className="flex items-center gap-2 rounded-full border border-border px-3 py-2 text-sm print:hidden"><Printer size={16} /> Print</button><button onClick={download} disabled={busy} className="flex items-center gap-2 rounded-full bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-60 print:hidden">{busy ? 'Preparing…' : <><Download size={16} /> PDF</>}</button><button onClick={async () => { await navigator.clipboard.writeText(window.location.href); window.alert('Link copied to clipboard') }} aria-label="Copy recipe link" className="rounded-full border border-border p-2"><Copy size={16} /></button></div> }
